# shell agnostic loading
source ~/.sh_profile

# zsh specific shell config

# Load the starship theme
eval "$(starship init zsh)"

# plugins
source ~/.config/antigen.zsh

antigen use oh-my-zsh

antigen bundle docker
antigen bundle git
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

