
# Setup for option-arrowkey
[window]
option_as_alt = "Both"

[keyboard]
bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bB" },
    { key = "Right", mods = "Alt", chars = "\u001bF" },
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars = "\u001bOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
]

# copy on select
[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/themes/blualism.toml"]
