# Default colors
[colors.primary]
background = '#071a24' # base
# background = '#555555' # base
foreground = '#d7d7d7' # text
# Bright and dim foreground colors
#dim_foreground = '#CAD3F5'    # text
#bright_foreground = '#CAD3F5' # text

# Cursor colors
[colors.cursor]
text = '#061822'
cursor = '#feaf3c'

[colors.vi_mode_cursor]
text = '#061822'   # base
cursor = '#feaf3c'

# Search colors
[colors.search.matches]
foreground = '#061822' # base
background = '#A5ADCB' # subtext0

[colors.search.focused_match]
foreground = '#061822' # base
background = '#A6DA95' # green

[colors.footer_bar]
foreground = '#061822' # base
background = '#A5ADCB' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#061822' # base
background = '#EED49F' # yellow

[colors.hints.end]
foreground = '#061822' # base
background = '#A5ADCB' # subtext0

# Selection colors
[colors.selection]
text = '#061822'       # base
background = '#F4DBD6' # rosewater

# Normal colors
[colors.normal]
black = '#1d485f'   # surface1
red = '#db662d'     # red
green = '#008eab'   # green
yellow = '#feaf3c'  # yellow
blue = '#255a62'    # blue
magenta = '#77dbf4' # pink
cyan = '#5fb1c2'    # teal
white = '#e5c49e'   # subtext1

# Bright colors
[colors.bright]
black = '#545d65'   # surface2
red = '#dd998a'     # red
green = '#739da8'   # green
yellow = '#ffd34a'  # yellow
blue = '#0bc7e3'    # blue
magenta = '#ef7b68' # pink
cyan = '#d0fefd'    # teal
white = '#ffe9d7'   # subtext0

# Dim colors
[colors.dim]
black = '#494D64'   # surface1
red = '#ED8796'     # red
green = '#A6DA95'   # green
yellow = '#EED49F'  # yellow
blue = '#8AADF4'    # blue
magenta = '#F5BDE6' # pink
cyan = '#8BD5CA'    # teal
white = '#B8C0E0'   # subtext1
